CMakeLists.txt, cmake/modules/FindASSIMP.cmake, cmake/modules/FindGLEW.cmake, cmake/modules/FindGLFW3.cmake, cmake/modules/FindGLM.cmake, cmake/modules/FindSOIL.cmake
I added the Find*.cmake files that you mentioned from Reddit. Also, I found a bug that I didn't realize last night when I was testing the CMake build- the resources, textures, and shaders aren't being detected by the IDE since it isn't aware of the bin/ directory. This might only be an issue on Linux and its not a terribly huge deal since the binaries are still being built and all the programs that don't use external resources run fine. I just wanted to push these changes first before rearranging the build structure.
At the bottom of the CMakeLists.txt you'll notice
`file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/resources DESTINATION ${CMAKE_CURRENT_BINARY_DIR})`
This should allow the resources to be moved over to the binaries, but it still isn't being found by the IDE. So this means the CMake …
=> Cmake features

src/5.advanced_lighting/2.gamma_correction/gamma_correction.cpp
I got an error when trying to make the latest commit on Ubuntu 14.04. Apparently, the gamma variable is already defined in [mathcalls.h](https://gcc.gnu.org/ml/gcc-help/2001-03/msg00285/mathcalls.h) which is included when math.h is included. I had no idea, but after changing 'gamma' to 'gammaEnabled' I was able to build no problem.
=> fixed Linux error with the gamma variable already being defined in mathcalls.h

README.md, includes/learnopengl/filesystem.h, includes/learnopengl/model.h, src/1.getting_started/4.textures/textures_combined.cpp, src/1.getting_started/5.transformations/transformations.cpp, src/1.getting_started/6.coordinate_systems/coordinate_systems_multiple_objects.cpp, src/1.getting_started/7.camera/camera_with_class.cpp, src/2.lighting/4.lighting_maps/lighting_maps_specular.cpp, src/2.lighting/5.light_casters/light_casters_spotlight_soft.cpp, src/2.lighting/6.multiple_lights/multiple_lights.cpp, src/3.model_loading/1.model_loading/model_rendered.cpp, src/4.advanced_opengl/1.depth_testing/depth_testing_func.cpp, src/4.advanced_opengl/10.instancing/instancing_asteroids_instanced.cpp, src/4.advanced_opengl/2.stencil_testing/stencil_testing.cpp, src/4.advanced_opengl/3.1.blending_discard/blending_discard.cpp, src/4.advanced_opengl/3.2.blending_sort/blending_sorted.cpp, src/4.advanced_opengl/5.framebuffers/framebuffers_screen_texture.cpp, src/4.advanced_opengl/6.cubemaps/cubemaps_skybox_optimized.cpp, src/5.advanced_lighting/1.advanced_lighting/advanced_lighting.cpp, src/5.advanced_lighting/2.gamma_correction/gamma_correction.cpp, src/5.advanced_lighting/3.1.shadow_mapping/shadow_mapping.cpp, src/5.advanced_lighting/3.2.point_shadows/point_shadows.cpp, src/5.advanced_lighting/3.3.csm/csm.cpp, src/5.advanced_lighting/4.normal_mapping/normal_mapping.cpp, src/5.advanced_lighting/5.parallax_mapping/parallax_mapping.cpp, src/5.advanced_lighting/6.hdr/hdr.cpp, src/5.advanced_lighting/7.bloom/bloom.cpp, src/5.advanced_lighting/8.deferred_shading/deferred_shading.cpp, src/5.advanced_lighting/9.ssao/ssao.cpp
Uses an environment variable to tell the program where to find resource files.
Shader sources are still search for in the current working directory.
From the readme:
> Note that using CodeBlocks or an IDE may have issues
> running the programs due to problems finding the shader
> and resource files.
This turned out to be a real problem with CLion, which places everything CMake related and all compiled binaries in its own hidden folders. To work around this I made it possible to set an environment variable (LOGL_ROOT_PATH for now). If that is set, then resource files are search there. If not, then the same ../../../ relative path as before is used.
=> Support for out-of-source builds.

CMakeLists.txt
Better to use the variables set by the various find_package calls than to hard-code the names.
=> Fixed linking with GLFW in Ubuntu.

src/5.advanced_lighting/8.deferred_shading/deferred_shading.cpp
gBuffer.
The texture was being set up as GL_RGB instead of GL_RGB16F which caused
negative components of normals to be set to 0.
=> Deferred Shading: Fixed bug with the normal texture component of the

src/4.advanced_opengl/10.instancing/instancing_asteroids_instanced.cpp
I noticed that the texture mapping was not working in the instancing example. This fix binds the rock models texture to the shaders sampler so texture mapping works.
=> Fix texture mapping in asteroid instancing example.

src/5.advanced_lighting/9.ssao/ssao_lighting.frag
It was not possible to view normals since its `draw_mode` was the same as the `draw_mode` for position.
=> Fix switching draw mode in SSAO deferred shader

src/5.advanced_lighting/8.2.deferred_shading_volumes/deferred_shading_volumes.cpp
Changed MSVC std::sqrtf call to simple std::sqrt - causes compile failure on mingw toolchain, as no such function is present.
=> Changed MSVC std::sqrtf call to simple std::sqrt on MinGW toolchain

src/5.advanced_lighting/7.bloom/7.bloom.fs
BloomColor was not initialized with a value and therefore could incorrectly bloom non-bright pixels.
Maybe... since the issue randomly started to happen on my system (i5-4570, GTX 760) without any hardware or software changes I know of. Even older versions of my program then suddenly had this problem and this was the only working fix which was mentioned in the comments section on the tutorial: https://learnopengl.com/#!Advanced-Lighting/Bloom#comment-2693931521
=> Fix Bloom in rare cases

src/6.pbr/1.1.lighting/1.1.pbr.fs
This may happen at certain hard to replicate viewing angles.
Theoretically clamp 0,1 should also be faster since SAT (saturate) is a free operation on output however since saturate only exists on HLSL we are at the mercy of the GLSL compiler to replace clamp 0,1 with SAT. Source: http://www.humus.name/Articles/Persson_LowLevelThinking.pdf#page=22
=> Fix rare graphical error showing a black box

src/6.pbr/1.1.lighting/1.1.pbr.fs
Is needed in addition to #92 to fix all graphical errors. Happens due to divide by 0 when `roughness = 0.0` and `NdotH = 1.0`.
Also use max to clamp similar fix for specular calculation instead of addition to fix the formula in normal cases
=> Fix another graphical error showing a black box

includes/learnopengl/mesh.h, includes/learnopengl/model.h
Hi, I removed the assimp dependency from the mesh header. I think that it is much easier to understand the purpose of the mesh class vs. the model class if assimp is only used in the model, which loads meshes.
=> decoupled assimp from mesh.h

src/6.pbr/1.1.lighting/lighting.cpp
А tiny fix to make the object grid form properly, As it stands integer division makes some spheres be positioned at same spot.
Sorry about commit garbage - first try ended up with broken CR/LF or something marking whole source as being modified.
=> Tutorial PBR 1.1 sphere grid construction fix

src/6.pbr/1.1.lighting/lighting.cpp, src/6.pbr/1.2.lighting_textured/lighting_textured.cpp
Well, after reiterating a bit more attentively this code snippet I'm here to atone my sins.
Issue is not in integer division, as it's still does it's work. Culprit is in implicit type conversion. 
To be more precise signed -> unsigned int conversion that takes place in position calculation and creates negative overflow.
Sorry for the mess, Joey)
=> Another take on PBR tutorials missing rows and columns

docker/.dockerignore, docker/Dockerfile, docker/ide.sh
This shows how it works https://streamable.com/gf74j
1. Execute `docker/ide.sh {PATH_TO_IDE_IN_HOME_DIRECTORY}`
2. Install video drivers inside docker container ([same as on host machine](https://github.com/mviereck/x11docker#dependencies))
_[This fix](https://github.com/JoeyDeVries/LearnOpenGL/issues/64#issuecomment-349908786) is required for build to work_
_I like my system free of development libraries that's why I try to make all my projects run in docker._
=> Build and run in docker

src/7.in_practice/3.2d_game/0.full_source/shaders/post_processing.frag
According to [here](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Fragment_shader_outputs) memory of a fragment shader variable is initialized with undefined values. Therefore it should be zeroed out.
=> Zero out memory from color variable

src/7.in_practice/2.text_rendering/text_rendering.cpp
Would it make sense to add a 'readme.md' to the text rendering source folder, telling what steps would be needed to download and install Freetype2?
Such as add Freetype2 to the includes folder and to the lib folder.  Also, change the font load path at line 91 in text_rendering.cpp from "fonts/arial.ttf" to "C:/Windows/Fonts/arial.ttf".
=> Fix 'use' and 'ID' in two places each, delete second main()

src/7.in_practice/2.text_rendering/readme.md
Step by step instructions on how to add Freetype2 to the text_rendering example, using VS2019 in Windows 10.
=> Add readme.md for the text_rendering example.

CMakeLists.txt
This prevents a link error on Ubuntu 18.04.
=> Link `freetype` for unix and not apple.

src/7.in_practice/2.text_rendering/text_rendering.cpp
`FileSystem::getPath()` returns a temporary object so we save the result in an `std::string` object (rather than a pointer).
This makes it work on Ubuntu 18.04 where it was failing previously.
=> Make font loading more reliably.

includes/learnopengl/model.h
Thank you very much for the great work on the tutorials!
This simple fix enables to import other types of objects that do not require the textures (e.g. .stl).
The calculation of the tangent and bitangent must be moved inside the if statement.
=> Fix texture coordinate tangent and bitangent calculation

src/7.in_practice/2.text_rendering/text_rendering.cpp
Fix for compile warning under GCC10 on Ubuntu Linux.
=> Fixed compile warning.

includes/learnopengl/model.h
Hi, again Joey!
This fix enables to handle more objects, for example, the [teapot](https://graphics.stanford.edu/courses/cs148-10-summer/as3/code/as3/teapot.obj) with no vertex normals given.
=> Generate smooth normals

src/5.advanced_lighting/9.ssao/9.ssao.fs
This isn't a big deal or perhaps something not worth while at all
but some version in glsl ```sample``` got turned into a keyword (for me it didn't work on 4.1 core) causing a shader compilation error in the ssao example.
[This spec shows it on page 25](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf).
My one argument for it is that up until this point everything has worked great (love the tutorial so much btw) on 4.1 core but I totally understand not wanting to worry about future versions.
=> Renamed sample -> samplePos because sample is a keyword in future glsl versions

src/8.guest/2020/oit/weighted_blended.cpp
I found this bug while implementing the OIT tutorial. ``glDisable(GL_DEPTH)`` gives out an OpenGL error on my AMD 5700 XT (Maybe this error slipped through because of GPU driver differences?)
=> Fix bug: glDisable(GL_DEPTH) -> glDisable(GL_DEPTH_TEST)

src/6.pbr/1.1.lighting/1.1.pbr.fs, src/6.pbr/1.2.lighting_textured/1.2.pbr.fs, src/6.pbr/2.1.1.ibl_irradiance_conversion/2.1.1.pbr.fs, src/6.pbr/2.1.2.ibl_irradiance/2.1.2.pbr.fs, src/6.pbr/2.2.1.ibl_specular/2.2.1.pbr.fs, src/6.pbr/2.2.2.ibl_specular_textured/2.2.2.pbr.fs
@JoeyDeVries Thanks a lot for your awesome tutorial!
Seems found a typo, should use `numerator` instead of `nominator`?
=> Fix typo: nominator to numerator.

src/4.advanced_opengl/5.2.framebuffers_exercise1/framebuffers_exercise1.cpp
Rotating both the Yaw and Pitch would cause the mirror to display whatever was in front but with Pitch * -1, this fixes this behaviour. Tested.
Before:
After:
=> Fix a minor bug in rear view mirror

src/4.advanced_opengl/6.1.cubemaps_skybox/cubemaps_skybox.cpp
In cubemaps_skybox.cpp, the second argument to glBufferDelete() should be &SkyboxVBO instead of &SkyboxVAO.
=> Fix glBufferDelete() argument mistake in cubemaps_skybox.cpp

src/6.pbr/1.1.lighting/1.1.pbr.fs, src/6.pbr/1.2.lighting_textured/1.2.pbr.fs, src/6.pbr/2.1.1.ibl_irradiance_conversion/2.1.1.pbr.fs, src/6.pbr/2.1.2.ibl_irradiance/2.1.2.pbr.fs, src/6.pbr/2.2.1.ibl_specular/2.2.1.pbr.fs, src/6.pbr/2.2.2.ibl_specular_textured/2.2.2.pbr.fs
4 is treated as a const int in OpenGL ES3/WebGL2 and fails to compile.
=> bugfix: (int)4 -> (float)4.0

.gitignore, CMakeLists.txt, build_windows.sh
The guest articles currently are not built by the CMake file, because they are in a different folder structure than the regular articles. This PR fixes that. This should make it easier for readers to test and and understand the topics discussed. There are some compile/linking issues with most guest articles, but I guess the authors can probably fix those easily. [Mine](https://learnopengl.com/Guest-Articles/2021/CSM) builds without hiccups for example, but the frustum culling project misses the assimp .dll.
I also added a shell script to make windows builds more convenient.
=> Guest article builds + windows build script.

CMakeLists.txt, includes/learnopengl/animator.h, includes/learnopengl/bone.h, src/8.guest/2020/skeletal_animation/anim_model.fs, src/8.guest/2020/skeletal_animation/anim_model.vs, src/8.guest/2020/skeletal_animation/skeletal_animation.cpp
Fixed syntax errors in animator.h, bone.h and skeletal_animation.cpp. I have also changed version code in shaders to 330 because GLSL compiler was logging errors regarding that. Thanks.
=> Fixed errors in skeletal animation code

src/8.guest/2020/skeletal_animation/skeletal_animation.cpp
The uniform name wasn't matching with what's declared in shader "anim_model.vs". It should be "finalBonesMatrices" instead of "finalBonesTransformations" which is corrected.
=> corrected uniform name for bone transformations

src/8.guest/2021/1.scene/1.scene_graph/scene_graph.cpp
Before only 1 planet was visualized.
I've used the same approach as in [frustum_culling.cpp](https://github.com/JoeyDeVries/LearnOpenGL/blob/166aeced4b950daf8f7617a8e68568a9e500970f/src/8.guest/2021/1.scene/2.frustum_culling/frustum_culling.cpp#L117).
=> Fix loading of entities in scene graph example

CMakeLists.txt, src/8.guest/2020/skeletal_animation/anim_model.vs
There was a bug in the skeletal animation guest article's vertex shader. This fixes it. Also I made it so that .dlls get copied to all the build directories because some projects (for example the skeletal animation one) use them. This is not the best solution but it works.
=> Skeletal animation project fix + windows DLL copy

README.md
CMake should be left to manage directory structure exclusively and run from the project root directory, along with the number of jobs that can be launched in parallel during the build process determined on the capabilities of the user's system.
=> An even simpler way to build on Mac.

README.md
That script was moved here https://github.com/01e9/ide-in-docker but it's too advanced, too much trouble
=> readme: removed outdated section "Linux building in Docker"

src/8.guest/2021/2.csm/shadow_mapping.cpp
Please see this comment: http://disq.us/p/2rdhett
One of the readers kindly pointed out that I used the wrong function here. 🥲  @JoeyDeVries would you be so kind to merge it, and change the function names in the article too is possible? This part, in the code block:
=> [CSM guest article] Fixed float::min usage instead of float::lowest

includes/learnopengl/entity.h
The `m_isDirty` flag is never set to false currently.
Also, `updateSelfAndChild()` should check if any child is dirty, not just the current `Entity`.
=> [scenegraph] Fix update of model matrix

src/6.pbr/1.1.lighting/1.1.pbr.vs, src/6.pbr/1.1.lighting/lighting.cpp, src/6.pbr/1.2.lighting_textured/1.2.pbr.vs, src/6.pbr/1.2.lighting_textured/lighting_textured.cpp, src/6.pbr/2.1.1.ibl_irradiance_conversion/2.1.1.pbr.vs, src/6.pbr/2.1.1.ibl_irradiance_conversion/ibl_irradiance_conversion.cpp, src/6.pbr/2.1.2.ibl_irradiance/2.1.2.pbr.vs, src/6.pbr/2.1.2.ibl_irradiance/ibl_irradiance.cpp, src/6.pbr/2.2.1.ibl_specular/2.2.1.pbr.vs, src/6.pbr/2.2.1.ibl_specular/ibl_specular.cpp, src/6.pbr/2.2.2.ibl_specular_textured/2.2.2.pbr.vs, src/6.pbr/2.2.2.ibl_specular_textured/ibl_specular_textured.cpp
I think normals are currently calculated incorrectly in the PBR vertex shaders. It is just a lucky coincidence that they work I guess because of the sphere models 🤔 
We should be multiplying the vertex normals with the proper normal matrix. While this PR does not change the result of the calculation, we should avoid someone copying this code and it not working in their engine and them spending hours debugging.
Let me know if I misunderstood something and the currect calculations are in fact correct.
=> Fixed normal calculation in PBR shaders

src/8.guest/2021/2.csm/10.debug_cascade.fs, src/8.guest/2021/2.csm/10.debug_cascade.vs, src/8.guest/2021/2.csm/10.debug_quad.vs, src/8.guest/2021/2.csm/10.debug_quad_depth.fs, src/8.guest/2021/2.csm/10.shadow_mapping.fs, src/8.guest/2021/2.csm/10.shadow_mapping.vs, src/8.guest/2021/2.csm/10.shadow_mapping_depth.fs, src/8.guest/2021/2.csm/10.shadow_mapping_depth.gs, src/8.guest/2021/2.csm/10.shadow_mapping_depth.vs, src/8.guest/2021/2.csm/shadow_mapping.cpp
1. Lower OpenGL demands: the demo works fine with v4.1. No need to require v4.6 which is not available on mac os.
2. Use actual framebuffer size to fix viewport issues on retina displays.
=> 2.3.csm: fix mac os issues

src/8.guest/2020/oit/composite.fs, src/8.guest/2020/oit/composite.vs, src/8.guest/2020/oit/screen.fs, src/8.guest/2020/oit/screen.vs, src/8.guest/2020/oit/solid.fs, src/8.guest/2020/oit/solid.vs, src/8.guest/2020/oit/transparent.fs, src/8.guest/2020/oit/transparent.vs, src/8.guest/2020/oit/weighted_blended.cpp
error output:
```
ERROR::SHADER_COMPILATION_ERROR of type: FRAGMENT
ERROR: 0:7: 'binding' : not supported for this version or the enabled extensions
ERROR: 0:7: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
-- --------------------------------------------------- --
ERROR::PROGRAM_LINKING_ERROR of type: PROGRAM
Program Link Failed for unknown reason.
-- --------------------------------------------------- --
```
OS & devices:  
1. Windows 11, AMD Radeon RX6750 XT  
2. Windows 10, NV GTX1650
=> fix: 8.guest.2020.oit: binding point supported since core 4.2
